version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: amar_postgres
    restart: always
    environment:
      POSTGRES_DB: AmarMovie_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Amarnath@8
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: