// <auto-generated />
using System;
using AmarShowsBook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AmarShowsBook.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260511155635_AddAdminUserFlags")]
    partial class AddAdminUserFlags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AmarShowsBook.Models.Admin.ActivityLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("IsError")
                        .HasColumnType("integer");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("activity_logs", (string)null);
                });

            modelBuilder.Entity("AmarShowsBook.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("AmarShowsBook.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("AmarShowsBook.Models.LiveStream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LiveStreams");
                });

            modelBuilder.Entity("AmarShowsBook.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("AmarShowsBook.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cast")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Director")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("AmarShowsBook.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("AmarShowsBook.Models.ShowSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LiveStreamId")
                        .HasColumnType("integer");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int?>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int?>("StandupShowId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LiveStreamId");

                    b.HasIndex("LocationId");

                    b.HasIndex("MovieId");

                    b.HasIndex("StandupShowId");

                    b.ToTable("ShowSchedules");
                });

            modelBuilder.Entity("AmarShowsBook.Models.StandupShow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comedian")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StandupShows");
                });

            modelBuilder.Entity("AmarShowsBook.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("States");
                });

            modelBuilder.Entity("AmarShowsBook.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pincode")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AmarShowsBook.Models.VwAdminUserManagement", b =>
                {
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("TotalBookings")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("numeric");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserMobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable((string)null);

                    b.ToView("vw_admin_user_management", (string)null);
                });

            modelBuilder.Entity("AmarShowsBook.Models.VwBookingCompleteDetails", b =>
                {
                    b.Property<DateTime?>("BookedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booked_at");

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    b.Property<string>("BookingRef")
                        .HasColumnType("text")
                        .HasColumnName("booking_ref");

                    b.Property<string>("BookingStatus")
                        .HasColumnType("text")
                        .HasColumnName("booking_status");

                    b.Property<int>("IsError")
                        .HasColumnType("integer")
                        .HasColumnName("is_error");

                    b.Property<decimal>("PayableAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("payable_amount");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("text");

                    b.Property<string>("ShowTitle")
                        .HasColumnType("text")
                        .HasColumnName("show_title");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text")
                        .HasColumnName("user_email");

                    b.ToTable((string)null);

                    b.ToView("vw_booking_complete_details", (string)null);
                });

            modelBuilder.Entity("AmarShowsBook.Models.VwBookingTransactionSummary", b =>
                {
                    b.Property<DateTime>("BookingCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<string>("BookingRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GatewayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IsPaymentError")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShowTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShowType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TransactionAmount")
                        .HasColumnType("numeric");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable((string)null);

                    b.ToView("vw_booking_transaction_summary", (string)null);
                });

            modelBuilder.Entity("AmarShowsBook.Models.VwInvoiceSummary", b =>
                {
                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.Property<string>("InvoiceStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IsInvoiceError")
                        .HasColumnType("integer")
                        .HasColumnName("is_invoice_error");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.ToTable((string)null);

                    b.ToView("vw_invoice_summary", (string)null);
                });

            modelBuilder.Entity("AmarShowsBook.Models.VwNotificationCenter", b =>
                {
                    b.Property<int>("IsError")
                        .HasColumnType("integer")
                        .HasColumnName("is_error");

                    b.Property<int>("NotificationId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable((string)null);

                    b.ToView("vw_notification_center", (string)null);
                });

            modelBuilder.Entity("AmarShowsBook.Models.VwRefundSummary", b =>
                {
                    b.Property<int>("IsRefundError")
                        .HasColumnType("integer")
                        .HasColumnName("is_refund_error");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("RefundId")
                        .HasColumnType("integer");

                    b.Property<string>("RefundStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable((string)null);

                    b.ToView("vw_refund_summary", (string)null);
                });

            modelBuilder.Entity("AmarShowsBook.Models.VwTicketValidationSummary", b =>
                {
                    b.Property<int>("IsSecurityIssue")
                        .HasColumnType("integer")
                        .HasColumnName("is_security_issue");

                    b.Property<int>("ValidationLogId")
                        .HasColumnType("integer");

                    b.Property<string>("ValidationResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable((string)null);

                    b.ToView("vw_ticket_validation_summary", (string)null);
                });

            modelBuilder.Entity("AmarShowsBook.Models.VwUserAccessMatrix", b =>
                {
                    b.Property<string>("ActionType")
                        .HasColumnType("text")
                        .HasColumnName("action_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ModuleCode")
                        .HasColumnType("text")
                        .HasColumnName("module_code");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text")
                        .HasColumnName("module_name");

                    b.Property<string>("PermissionCode")
                        .HasColumnType("text")
                        .HasColumnName("permission_code");

                    b.Property<string>("PermissionName")
                        .HasColumnType("text")
                        .HasColumnName("permission_name");

                    b.Property<string>("RoleCode")
                        .HasColumnType("text")
                        .HasColumnName("role_code");

                    b.Property<string>("RoleName")
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text")
                        .HasColumnName("user_email");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.ToTable((string)null);

                    b.ToView("vw_user_access_matrix", (string)null);
                });

            modelBuilder.Entity("AmarShowsBook.Models.VwUserApplicationMenu", b =>
                {
                    b.Property<bool>("CanCreate")
                        .HasColumnType("boolean")
                        .HasColumnName("can_create");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("can_delete");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("boolean")
                        .HasColumnName("can_update");

                    b.Property<bool>("CanView")
                        .HasColumnType("boolean")
                        .HasColumnName("can_view");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("IconName")
                        .HasColumnType("text")
                        .HasColumnName("icon_name");

                    b.Property<string>("MenuCode")
                        .HasColumnType("text")
                        .HasColumnName("menu_code");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_id");

                    b.Property<int>("MenuLevel")
                        .HasColumnType("integer")
                        .HasColumnName("menu_level");

                    b.Property<string>("MenuName")
                        .HasColumnType("text")
                        .HasColumnName("menu_name");

                    b.Property<string>("RoleCode")
                        .HasColumnType("text")
                        .HasColumnName("role_code");

                    b.Property<string>("RoutePath")
                        .HasColumnType("text")
                        .HasColumnName("route_path");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.ToTable((string)null);

                    b.ToView("vw_user_application_menus", (string)null);
                });

            modelBuilder.Entity("AmarShowsBook.Models.VwWalletSummary", b =>
                {
                    b.Property<decimal>("BlockedBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("blocked_balance");

                    b.Property<DateTime?>("LastTransactionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_transaction_at");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("integer")
                        .HasColumnName("loyalty_points");

                    b.Property<decimal>("TotalCredits")
                        .HasColumnType("numeric")
                        .HasColumnName("total_credits");

                    b.Property<decimal>("TotalDebits")
                        .HasColumnType("numeric")
                        .HasColumnName("total_debits");

                    b.Property<int>("TotalWalletTransactions")
                        .HasColumnType("integer")
                        .HasColumnName("total_wallet_transactions");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_email");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.Property<decimal>("WalletBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("wallet_balance");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer")
                        .HasColumnName("wallet_id");

                    b.Property<string>("WalletStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("wallet_status");

                    b.ToTable((string)null);

                    b.ToView("vw_wallet_summary", (string)null);
                });

            modelBuilder.Entity("AmarShowsBook.Models.District", b =>
                {
                    b.HasOne("AmarShowsBook.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("AmarShowsBook.Models.ShowSchedule", b =>
                {
                    b.HasOne("AmarShowsBook.Models.LiveStream", "LiveStream")
                        .WithMany()
                        .HasForeignKey("LiveStreamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AmarShowsBook.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmarShowsBook.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AmarShowsBook.Models.StandupShow", "StandupShow")
                        .WithMany()
                        .HasForeignKey("StandupShowId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LiveStream");

                    b.Navigation("Location");

                    b.Navigation("Movie");

                    b.Navigation("StandupShow");
                });

            modelBuilder.Entity("AmarShowsBook.Models.State", b =>
                {
                    b.HasOne("AmarShowsBook.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
