-- AmarShowsBook enterprise schema rebuild script
-- Run on an empty PostgreSQL database.
-- Order: extensions -> functions -> tables -> foreign keys -> indexes -> triggers -> seed data -> views.

BEGIN;

SET check_function_bodies = off;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SEQUENCE IF NOT EXISTS public.booking_ref_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS public.refund_ref_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE FUNCTION public.fn_update_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_set_booking_reference()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.booking_ref IS NULL OR btrim(NEW.booking_ref) = '' THEN
        NEW.booking_ref := 'BK' || to_char(CURRENT_TIMESTAMP, 'YYYYMMDD') || lpad(nextval('public.booking_ref_seq')::text, 6, '0');
    END IF;

    IF NEW.original_amount IS NULL THEN
        NEW.original_amount := NEW.total_amount;
    END IF;

    IF NEW.payable_amount IS NULL THEN
        NEW.payable_amount := GREATEST(
            COALESCE(NEW.total_amount, 0)
            + COALESCE(NEW.tax_amount, 0)
            + COALESCE(NEW.convenience_fee, 0)
            - COALESCE(NEW.discount_amount, 0)
            - COALESCE(NEW.wallet_amount_used, 0),
            0
        );
    END IF;

    IF NEW.payment_status IS NULL THEN
        NEW.payment_status := 'PENDING';
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_track_booking_status()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.booking_status IS DISTINCT FROM NEW.booking_status THEN
        INSERT INTO public.booking_status_history
            (booking_id, old_status, new_status, changed_by, remarks, created_at)
        VALUES
            (NEW.id, OLD.booking_status, NEW.booking_status, COALESCE(NEW.updated_by, CURRENT_USER), 'Booking status changed', CURRENT_TIMESTAMP);

        INSERT INTO public.booking_history
            (booking_id, user_id, action, old_status, new_status, old_value, new_value, remarks, created_at)
        VALUES
            (NEW.id, NEW.user_id, 'STATUS_CHANGED', OLD.booking_status, NEW.booking_status, to_jsonb(OLD), to_jsonb(NEW), 'Booking status changed', CURRENT_TIMESTAMP);
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_assign_default_role()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_role_id bigint;
BEGIN
    SELECT id INTO v_role_id
    FROM public.roles
    WHERE role_code = 'USER'
    LIMIT 1;

    IF v_role_id IS NOT NULL THEN
        INSERT INTO public.user_roles (user_id, role_id, assigned_by, is_active)
        VALUES (NEW."Id", v_role_id, NULL, true)
        ON CONFLICT DO NOTHING;

        INSERT INTO public.user_role_mappings (user_id, role_id, assigned_by, is_active)
        VALUES (NEW."Id", v_role_id, NULL, true)
        ON CONFLICT DO NOTHING;
    END IF;

    INSERT INTO public.user_wallets (user_id, wallet_balance, blocked_balance, loyalty_points, wallet_status)
    VALUES (NEW."Id", 0, 0, 0, 'ACTIVE')
    ON CONFLICT (user_id) DO NOTHING;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_refund_audit()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO public.refund_history
        (refund_id, refund_status_old, refund_status_new, remarks, changed_by, metadata, created_at)
    VALUES
        (NEW.id, OLD.refund_status, NEW.refund_status, COALESCE(NEW.admin_notes, NEW.approval_remarks), COALESCE(NEW.updated_by, CURRENT_USER), to_jsonb(NEW), CURRENT_TIMESTAMP);

    INSERT INTO public.refund_action_logs
        (refund_id, refund_ref, action_name, action_by, action_time, action_notes)
    VALUES
        (NEW.id, NEW.refund_ref, COALESCE(NEW.workflow_action, NEW.refund_status), COALESCE(NEW.updated_by, CURRENT_USER), CURRENT_TIMESTAMP, COALESCE(NEW.admin_notes, NEW.failure_reason));

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_wallet_balance_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF COALESCE(NEW.status, NEW.transaction_status, 'SUCCESS') = 'SUCCESS' THEN
        UPDATE public.user_wallets
        SET wallet_balance =
                CASE
                    WHEN NEW.entry_type = 'CREDIT' THEN wallet_balance + NEW.amount
                    WHEN NEW.entry_type = 'DEBIT' THEN GREATEST(wallet_balance - NEW.amount, 0)
                    ELSE wallet_balance
                END,
            last_transaction_at = CURRENT_TIMESTAMP,
            updated_at = CURRENT_TIMESTAMP
        WHERE id = NEW.wallet_id;
    END IF;

    RETURN NEW;
END;
$$;

SET check_function_bodies = on;

CREATE TABLE IF NOT EXISTS public."Countries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code" text NOT NULL,
    "Name" text NOT NULL
);

CREATE TABLE IF NOT EXISTS public."States" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "CountryId" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Districts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "StateId" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Regions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CountryId" integer NOT NULL,
    "StateId" integer NOT NULL,
    "DistrictId" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Locations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Country" text NOT NULL,
    "State" text NOT NULL,
    "Area" text NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Movies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" text NOT NULL,
    "Director" text,
    "Producer" text NOT NULL,
    "Cast" text NOT NULL,
    "Duration" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."StandupShows" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" text NOT NULL,
    "Comedian" text NOT NULL,
    "Duration" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."LiveStreams" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" text NOT NULL,
    "Host" text NOT NULL,
    "Duration" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "Password" text NOT NULL,
    "Mobile" text NOT NULL,
    "Address" text,
    "Genre" text NOT NULL DEFAULT '',
    "Language" text,
    "ProfileImagePath" text,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" timestamp with time zone,
    "Country" text,
    "CreatedBy" text,
    "District" text,
    "Pincode" text,
    "State" text,
    "UpdatedBy" text,
    is_active boolean DEFAULT true,
    is_deleted boolean DEFAULT false,
    "IsActive" boolean NOT NULL DEFAULT true,
    "IsDeleted" boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS public."DeletedUsers" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_user_id bigint NOT NULL,
    name text,
    email text,
    mobile text,
    address text,
    country text,
    state text,
    district text,
    pincode text,
    language text,
    genre text,
    profile_image_path text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    deleted_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_by text,
    is_revoked boolean DEFAULT false,
    revoke_at timestamp without time zone,
    revoked_by text
);

CREATE TABLE IF NOT EXISTS public.roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code varchar(100) NOT NULL UNIQUE,
    role_name varchar(255) NOT NULL,
    role_description text,
    is_system_role boolean DEFAULT false,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(255),
    updated_by varchar(255)
);

CREATE TABLE IF NOT EXISTS public.application_modules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_code varchar(100) NOT NULL UNIQUE,
    module_name varchar(255) NOT NULL,
    module_description text,
    route_path varchar(500),
    icon_name varchar(100),
    display_order integer DEFAULT 0,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.application_menus (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_code varchar(100) NOT NULL UNIQUE,
    menu_name varchar(255) NOT NULL,
    parent_menu_id bigint,
    module_id bigint,
    route_path varchar(500),
    icon_name varchar(100),
    menu_level integer DEFAULT 1,
    display_order integer DEFAULT 0,
    is_visible boolean DEFAULT true,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code varchar(150) NOT NULL UNIQUE,
    permission_name varchar(255) NOT NULL,
    module_id bigint NOT NULL,
    action_type varchar(50) NOT NULL,
    description text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.user_roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    assigned_by bigint,
    assigned_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamp without time zone,
    is_active boolean DEFAULT true,
    UNIQUE (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.user_role_mappings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    assigned_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    assigned_by bigint,
    is_active boolean DEFAULT true,
    UNIQUE (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.role_permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL,
    granted_by bigint,
    granted_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.role_menu_access (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id bigint NOT NULL,
    menu_id bigint NOT NULL,
    can_view boolean DEFAULT true,
    can_create boolean DEFAULT false,
    can_update boolean DEFAULT false,
    can_delete boolean DEFAULT false,
    assigned_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    assigned_by bigint,
    UNIQUE (role_id, menu_id)
);

CREATE TABLE IF NOT EXISTS public.venues (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_code varchar(50) NOT NULL UNIQUE,
    venue_name varchar(255) NOT NULL,
    venue_type varchar(50),
    country varchar(100),
    state varchar(100),
    city varchar(100),
    address text,
    postal_code varchar(20),
    contact_email varchar(255),
    contact_mobile varchar(50),
    total_screens integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_active boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.theatre_screens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id integer NOT NULL,
    screen_name varchar(100) NOT NULL,
    total_seats integer NOT NULL,
    screen_type varchar(50),
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.screens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id bigint NOT NULL,
    screen_code varchar(50) NOT NULL,
    screen_name varchar(255) NOT NULL,
    total_seats integer NOT NULL DEFAULT 70,
    screen_type varchar(50) NOT NULL DEFAULT 'STANDARD',
    audio_system varchar(100) NOT NULL DEFAULT 'STANDARD',
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (venue_id, screen_code)
);

CREATE TABLE IF NOT EXISTS public.seat_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name varchar(100) NOT NULL,
    category_code varchar(50) NOT NULL UNIQUE,
    price_multiplier numeric(10,2) DEFAULT 1,
    color_code varchar(20),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.seats (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screen_id bigint NOT NULL,
    seat_category_id bigint NOT NULL,
    row_name varchar(10) NOT NULL,
    seat_number varchar(10) NOT NULL,
    display_label varchar(20),
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (screen_id, row_name, seat_number)
);

CREATE TABLE IF NOT EXISTS public.screen_seats (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screen_id bigint NOT NULL,
    "ScheduleId" integer NOT NULL,
    seat_row varchar(10) NOT NULL,
    seat_number varchar(10) NOT NULL,
    seat_category varchar(50),
    seat_price numeric(15,2) NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public."ShowSchedules" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MovieId" integer,
    "StandupShowId" integer,
    "LiveStreamId" integer,
    "LocationId" integer NOT NULL,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone NOT NULL,
    "Type" text NOT NULL DEFAULT '',
    screen_id bigint
);

CREATE TABLE IF NOT EXISTS public.show_seat_pricing (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id integer NOT NULL,
    seat_category_id bigint NOT NULL,
    base_price numeric(15,2) NOT NULL,
    tax_amount numeric(15,2) DEFAULT 0,
    convenience_fee numeric(15,2) DEFAULT 0,
    final_price numeric(15,2) GENERATED ALWAYS AS (base_price + tax_amount + convenience_fee) STORED,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (schedule_id, seat_category_id)
);

CREATE TABLE IF NOT EXISTS public.coupons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_code varchar(100) NOT NULL UNIQUE,
    coupon_name varchar(255) NOT NULL,
    description text,
    discount_type varchar(50) NOT NULL,
    discount_value numeric(15,2) NOT NULL,
    minimum_booking_amount numeric(15,2) DEFAULT 0,
    maximum_discount_amount numeric(15,2),
    usage_limit integer,
    usage_per_user integer DEFAULT 1,
    used_count integer DEFAULT 0,
    valid_from timestamp without time zone NOT NULL,
    valid_to timestamp without time zone NOT NULL,
    coupon_status varchar(50) DEFAULT 'ACTIVE',
    applicable_show_type varchar(50),
    applicable_payment_method varchar(50),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(255),
    updated_by varchar(255),
    metadata jsonb,
    CONSTRAINT chk_coupon_discount_type CHECK (discount_type IN ('PERCENTAGE', 'FLAT', 'CASHBACK')),
    CONSTRAINT chk_coupon_status CHECK (coupon_status IN ('ACTIVE', 'INACTIVE', 'EXPIRED'))
);

CREATE TABLE IF NOT EXISTS public.bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_ref varchar(100) NOT NULL UNIQUE,
    user_id bigint NOT NULL,
    schedule_id integer NOT NULL,
    booking_status varchar(50) NOT NULL DEFAULT 'PENDING',
    total_amount numeric(15,2) NOT NULL,
    total_tickets integer NOT NULL DEFAULT 1,
    booking_source varchar(50) DEFAULT 'WEB',
    remarks text,
    booked_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    cancelled_at timestamp without time zone,
    cancellation_reason text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(255),
    updated_by varchar(255),
    is_deleted boolean DEFAULT false,
    coupon_id bigint,
    original_amount numeric(15,2),
    discount_amount numeric(15,2) DEFAULT 0,
    payable_amount numeric(15,2),
    tax_amount numeric(15,2) DEFAULT 0,
    convenience_fee numeric(15,2) DEFAULT 0,
    wallet_amount_used numeric(15,2) DEFAULT 0,
    loyalty_points_used bigint DEFAULT 0,
    cashback_amount numeric(15,2) DEFAULT 0,
    transaction_id bigint,
    payment_status varchar(50) DEFAULT 'PENDING',
    confirmed_at timestamp without time zone,
    refund_status varchar(50),
    metadata jsonb,
    CONSTRAINT chk_booking_status CHECK (booking_status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'FAILED', 'REFUNDED')),
    CONSTRAINT chk_total_amount CHECK (total_amount >= 0),
    CONSTRAINT chk_total_tickets CHECK (total_tickets > 0)
);

CREATE TABLE IF NOT EXISTS public.transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_ref varchar(100) NOT NULL UNIQUE,
    user_id bigint NOT NULL,
    transaction_type varchar(50) NOT NULL,
    payment_method varchar(50),
    amount numeric(15,2) NOT NULL,
    currency varchar(10) DEFAULT 'INR',
    status varchar(30) NOT NULL,
    gateway_name varchar(100),
    gateway_transaction_id varchar(255),
    booking_id bigint,
    description text,
    failure_reason text,
    ip_address varchar(45),
    user_agent text,
    metadata jsonb,
    initiated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    gateway_status_code varchar(100),
    refunded_amount numeric(15,2) DEFAULT 0,
    refund_status varchar(50),
    reconciliation_status varchar(50) DEFAULT 'PENDING',
    gateway_response jsonb,
    fraud_score numeric(5,2),
    is_suspicious boolean DEFAULT false,
    device_fingerprint text,
    payment_source varchar(50),
    retry_count integer DEFAULT 0,
    is_deleted boolean DEFAULT false,
    CONSTRAINT chk_transaction_status CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', 'REFUNDED')),
    CONSTRAINT chk_transaction_amount CHECK (amount > 0)
);

CREATE TABLE IF NOT EXISTS public.booking_drafts (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" bigint NOT NULL,
    "ScheduleId" integer NOT NULL,
    "SeatNumbers" text NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public."PaymentSessions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BookingId" bigint NOT NULL,
    "SessionToken" text NOT NULL UNIQUE,
    "Status" text NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS public.booking_transactions (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BookingId" bigint NOT NULL,
    "TransactionRef" text NOT NULL UNIQUE,
    "PaymentMethod" text NOT NULL,
    "Amount" numeric NOT NULL,
    "PaymentStatus" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "PaidAt" timestamp with time zone
);

CREATE TABLE IF NOT EXISTS public.booking_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id bigint NOT NULL,
    ticket_type varchar(50),
    quantity integer NOT NULL DEFAULT 1,
    unit_price numeric(15,2) NOT NULL,
    total_price numeric(15,2) NOT NULL,
    attendee_name varchar(255),
    attendee_mobile varchar(20),
    attendee_email varchar(255),
    metadata jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.booking_seats (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id bigint NOT NULL,
    screen_seat_id bigint NOT NULL,
    booking_item_id bigint,
    seat_price numeric(15,2),
    booking_status varchar(50) DEFAULT 'LOCKED',
    qr_code text,
    checked_in_at timestamp without time zone,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.tickets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id bigint NOT NULL,
    ticket_number varchar(100) NOT NULL UNIQUE,
    attendee_name varchar(255),
    seat_number varchar(50),
    qr_code text,
    ticket_status varchar(50) DEFAULT 'ACTIVE',
    issued_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    checked_in_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    qr_token uuid DEFAULT gen_random_uuid(),
    qr_generated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    qr_expiry_at timestamp without time zone,
    validation_status varchar(50) DEFAULT 'NOT_SCANNED',
    validation_count integer DEFAULT 0,
    last_scanned_at timestamp without time zone,
    last_scanned_gate varchar(100),
    security_hash text,
    CONSTRAINT chk_ticket_status CHECK (ticket_status IN ('ACTIVE', 'USED', 'CANCELLED', 'EXPIRED')),
    CONSTRAINT chk_ticket_validation_status CHECK (validation_status IN ('NOT_SCANNED', 'SCANNED', 'BLOCKED', 'EXPIRED', 'CANCELLED'))
);

CREATE TABLE IF NOT EXISTS public.booked_seats (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id bigint NOT NULL,
    schedule_id integer NOT NULL,
    seat_id bigint NOT NULL,
    ticket_id bigint,
    seat_price numeric(15,2) NOT NULL,
    booking_status varchar(50) DEFAULT 'BOOKED',
    locked_until timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.seat_locks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id varchar(255),
    user_id bigint,
    schedule_id integer NOT NULL,
    screen_seat_id bigint NOT NULL,
    locked_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    booking_id bigint,
    lock_status varchar(50) DEFAULT 'LOCKED',
    released_at timestamp without time zone,
    ip_address varchar(45),
    user_agent text,
    remarks text,
    metadata jsonb,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(255),
    updated_by varchar(255),
    CONSTRAINT chk_seat_lock_status CHECK (lock_status IN ('LOCKED', 'RELEASED', 'CONFIRMED', 'EXPIRED'))
);

CREATE TABLE IF NOT EXISTS public.booking_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id bigint NOT NULL,
    user_id bigint,
    action varchar(50) NOT NULL,
    old_status varchar(50),
    new_status varchar(50),
    old_value jsonb,
    new_value jsonb,
    remarks text,
    ip_address varchar(45),
    user_agent text,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.booking_status_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id bigint NOT NULL,
    old_status varchar(50),
    new_status varchar(50),
    changed_by varchar(255),
    remarks text,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.booking_transaction_audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id integer,
    transaction_id integer,
    user_id integer,
    action_type varchar(50),
    old_data jsonb,
    new_data jsonb,
    changed_by varchar(255),
    changed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.coupon_usage (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id bigint NOT NULL,
    booking_id bigint,
    transaction_id bigint,
    user_id bigint NOT NULL,
    coupon_code varchar(100),
    original_amount numeric(15,2),
    discount_amount numeric(15,2),
    final_amount numeric(15,2),
    usage_status varchar(50) DEFAULT 'SUCCESS',
    used_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    metadata jsonb
);

CREATE TABLE IF NOT EXISTS public.coupon_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_id bigint NOT NULL,
    action_type varchar(100),
    old_value jsonb,
    new_value jsonb,
    changed_by varchar(255),
    remarks text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.refunds (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_ref varchar(100) NOT NULL UNIQUE DEFAULT ('RF' || to_char(CURRENT_TIMESTAMP, 'YYYYMMDD') || lpad(nextval('public.refund_ref_seq')::text, 6, '0')),
    booking_id bigint NOT NULL,
    transaction_id bigint NOT NULL,
    user_id bigint NOT NULL,
    refund_amount numeric(15,2) NOT NULL,
    refund_reason text,
    refund_status varchar(50) NOT NULL DEFAULT 'PENDING',
    refund_method varchar(50),
    gateway_refund_id varchar(255),
    gateway_response jsonb,
    requested_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    processed_at timestamp without time zone,
    approved_by varchar(255),
    approval_remarks text,
    failure_reason text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(255),
    updated_by varchar(255),
    is_deleted boolean DEFAULT false,
    approved_at timestamp without time zone,
    rejected_by text,
    rejected_at timestamp without time zone,
    retried_by text,
    retried_at timestamp without time zone,
    admin_notes text,
    workflow_action text,
    CONSTRAINT chk_refund_amount CHECK (refund_amount > 0),
    CONSTRAINT chk_refund_status CHECK (refund_status IN ('PENDING', 'APPROVED', 'PROCESSING', 'SUCCESS', 'FAILED', 'REJECTED'))
);

CREATE TABLE IF NOT EXISTS public.refund_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_id bigint NOT NULL,
    refund_status_old varchar(50),
    refund_status_new varchar(50),
    remarks text,
    changed_by varchar(255),
    ip_address varchar(45),
    user_agent text,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.refund_action_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_id bigint NOT NULL,
    refund_ref text,
    action_name text NOT NULL,
    action_by text,
    action_time timestamp without time zone NOT NULL DEFAULT now(),
    action_notes text,
    ip_address text,
    created_at timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.invoices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number varchar(100) NOT NULL UNIQUE,
    booking_id bigint NOT NULL,
    transaction_id bigint,
    user_id bigint NOT NULL,
    invoice_type varchar(50) NOT NULL,
    invoice_status varchar(50) DEFAULT 'GENERATED',
    invoice_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    billing_name varchar(255),
    billing_email varchar(255),
    billing_mobile varchar(50),
    billing_address text,
    billing_state varchar(100),
    billing_country varchar(100),
    gstin varchar(50),
    subtotal_amount numeric(15,2),
    cgst_amount numeric(15,2) DEFAULT 0,
    sgst_amount numeric(15,2) DEFAULT 0,
    igst_amount numeric(15,2) DEFAULT 0,
    tax_percentage numeric(5,2),
    discount_amount numeric(15,2) DEFAULT 0,
    total_amount numeric(15,2),
    currency varchar(10) DEFAULT 'INR',
    invoice_pdf_url text,
    qr_code text,
    notes text,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(255),
    updated_by varchar(255),
    CONSTRAINT chk_invoice_type CHECK (invoice_type IN ('BOOKING', 'REFUND', 'CREDIT_NOTE')),
    CONSTRAINT chk_invoice_status CHECK (invoice_status IN ('GENERATED', 'CANCELLED', 'FAILED'))
);

CREATE TABLE IF NOT EXISTS public.invoice_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id bigint NOT NULL,
    item_type varchar(100),
    item_name varchar(255),
    item_description text,
    quantity integer DEFAULT 1,
    unit_price numeric(15,2),
    taxable_amount numeric(15,2),
    tax_percentage numeric(5,2),
    tax_amount numeric(15,2),
    total_amount numeric(15,2),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.invoice_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id bigint NOT NULL,
    action_type varchar(100),
    old_value jsonb,
    new_value jsonb,
    changed_by varchar(255),
    remarks text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.refund_invoices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_id bigint NOT NULL,
    original_invoice_id bigint NOT NULL,
    refund_invoice_id bigint NOT NULL,
    refund_amount numeric(15,2),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.user_wallets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL UNIQUE,
    wallet_balance numeric(15,2) DEFAULT 0,
    blocked_balance numeric(15,2) DEFAULT 0,
    loyalty_points bigint DEFAULT 0,
    wallet_status varchar(50) DEFAULT 'ACTIVE',
    last_transaction_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_wallet_balance CHECK (wallet_balance >= 0),
    CONSTRAINT chk_blocked_balance CHECK (blocked_balance >= 0),
    CONSTRAINT chk_wallet_status CHECK (wallet_status IN ('ACTIVE', 'BLOCKED', 'SUSPENDED'))
);

CREATE TABLE IF NOT EXISTS public.wallet_transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id bigint NOT NULL,
    user_id bigint NOT NULL,
    booking_id bigint,
    transaction_id bigint,
    refund_id bigint,
    transaction_ref varchar(100) NOT NULL UNIQUE,
    transaction_type varchar(50) NOT NULL,
    entry_type varchar(20) NOT NULL,
    amount numeric(15,2) NOT NULL,
    opening_balance numeric(15,2),
    closing_balance numeric(15,2),
    remarks text,
    transaction_status varchar(50) DEFAULT 'SUCCESS',
    metadata jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(255),
    description text,
    status varchar(30) DEFAULT 'SUCCESS',
    reference_type varchar(50),
    reference_id bigint,
    balance_before numeric(15,2) DEFAULT 0,
    balance_after numeric(15,2) DEFAULT 0,
    payment_method varchar(50),
    gateway_name varchar(100),
    gateway_reference varchar(255),
    is_deleted boolean DEFAULT false,
    updated_by bigint,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_wallet_entry_type CHECK (entry_type IN ('CREDIT', 'DEBIT')),
    CONSTRAINT chk_wallet_transaction_status CHECK (status IN ('SUCCESS', 'FAILED', 'PENDING', 'CANCELLED')),
    CONSTRAINT chk_wallet_tx_type CHECK (transaction_type IN ('TOPUP', 'BOOKING', 'PURCHASE', 'REFUND', 'FOOD', 'BONUS', 'CASHBACK', 'WITHDRAWAL'))
);

CREATE TABLE IF NOT EXISTS public.loyalty_config (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_name varchar(100),
    points_per_amount numeric(10,2),
    minimum_redeem_points bigint,
    point_value numeric(10,2),
    max_redeem_percentage numeric(5,2),
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.loyalty_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    booking_id bigint,
    wallet_transaction_id bigint,
    points_earned bigint DEFAULT 0,
    points_redeemed bigint DEFAULT 0,
    opening_points bigint,
    closing_points bigint,
    remarks text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.notification_templates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_code varchar(100) NOT NULL UNIQUE,
    template_name varchar(255) NOT NULL,
    notification_type varchar(50) NOT NULL,
    subject text,
    body text NOT NULL,
    variables jsonb,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(255),
    updated_by varchar(255),
    CONSTRAINT chk_notification_type CHECK (notification_type IN ('EMAIL', 'SMS', 'PUSH', 'IN_APP', 'WHATSAPP'))
);

CREATE TABLE IF NOT EXISTS public.user_notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    template_id bigint,
    notification_type varchar(50) NOT NULL,
    title text,
    message text NOT NULL,
    status varchar(50) DEFAULT 'PENDING',
    priority varchar(20) DEFAULT 'NORMAL',
    recipient_email varchar(255),
    recipient_mobile varchar(20),
    push_token text,
    sent_at timestamp without time zone,
    delivered_at timestamp without time zone,
    read_at timestamp without time zone,
    retry_count integer DEFAULT 0,
    failure_reason text,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_notification_status CHECK (status IN ('PENDING', 'PROCESSING', 'SENT', 'DELIVERED', 'READ', 'FAILED'))
);

CREATE TABLE IF NOT EXISTS public.notification_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id bigint NOT NULL,
    action_type varchar(100),
    old_value jsonb,
    new_value jsonb,
    changed_by varchar(255),
    remarks text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.notification_queue (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint,
    notification_type varchar(50),
    recipient varchar(255),
    subject text,
    message text,
    delivery_status varchar(50) DEFAULT 'PENDING',
    retry_count integer DEFAULT 0,
    sent_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    metadata jsonb
);

CREATE TABLE IF NOT EXISTS public.otp_management (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint,
    otp_code varchar(20) NOT NULL,
    otp_type varchar(50) NOT NULL,
    delivery_type varchar(50) NOT NULL,
    recipient varchar(255) NOT NULL,
    status varchar(50) DEFAULT 'ACTIVE',
    expires_at timestamp without time zone NOT NULL,
    verified_at timestamp without time zone,
    retry_count integer DEFAULT 0,
    ip_address varchar(50),
    user_agent text,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_otp_status CHECK (status IN ('ACTIVE', 'USED', 'EXPIRED', 'FAILED'))
);

CREATE TABLE IF NOT EXISTS public.ticket_validation_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id bigint NOT NULL,
    booking_id bigint,
    user_id bigint,
    scanned_qr_token uuid,
    validation_status varchar(50),
    validation_result varchar(100),
    gate_name varchar(100),
    device_id varchar(255),
    scanner_user varchar(255),
    scanner_ip varchar(45),
    latitude numeric(10,7),
    longitude numeric(10,7),
    remarks text,
    metadata jsonb,
    scanned_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.scanner_devices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_code varchar(100) NOT NULL UNIQUE,
    device_name varchar(255),
    venue_id bigint,
    screen_id bigint,
    gate_name varchar(100),
    device_status varchar(50) DEFAULT 'ACTIVE',
    last_active_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.access_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint,
    role_id bigint,
    permission_code varchar(150),
    module_name varchar(255),
    endpoint text,
    action_name varchar(255),
    access_status varchar(50),
    ip_address varchar(50),
    user_agent text,
    remarks text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.activity_logs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer,
    action text NOT NULL,
    module text NOT NULL,
    entity_type text,
    entity_id integer,
    description text,
    request_method text,
    endpoint text,
    ip_address text,
    user_agent text,
    status text,
    old_value jsonb,
    new_value jsonb,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT now(),
    error_code text,
    error_message text,
    error_source text,
    stack_trace text,
    is_error integer DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.dummy_cards (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CardNo" text NOT NULL,
    "HolderName" text NOT NULL,
    "Expiry" text NOT NULL,
    "CVV" text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.frontend_version_control (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version varchar(50) NOT NULL UNIQUE,
    build_number varchar(50),
    environment varchar(50) NOT NULL,
    release_name varchar(255),
    release_notes text,
    commit_hash varchar(255),
    branch_name varchar(100),
    deployment_status varchar(50) NOT NULL,
    application_url varchar(500),
    artifact_url varchar(500),
    deployed_by varchar(255),
    deployed_at timestamp without time zone,
    rollback_version varchar(50),
    failure_reason text,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.menu_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id bigint,
    action_type varchar(50),
    old_value jsonb,
    new_value jsonb,
    changed_by varchar(255),
    remarks text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.system_announcements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    announcement_title varchar(255),
    announcement_message text,
    audience_type varchar(50),
    priority varchar(50),
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    is_active boolean DEFAULT true,
    created_by varchar(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.tax_configuration (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tax_name varchar(100) NOT NULL,
    tax_code varchar(50) NOT NULL UNIQUE,
    tax_type varchar(50) NOT NULL,
    tax_percentage numeric(5,2) NOT NULL,
    applicable_from timestamp without time zone NOT NULL,
    applicable_to timestamp without time zone,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.webhook_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_system varchar(100),
    event_type varchar(100),
    reference_id varchar(255),
    payload jsonb,
    response_payload jsonb,
    processing_status varchar(50),
    error_message text,
    received_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    processed_at timestamp without time zone
);

CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory" (
    "MigrationId" varchar(150) NOT NULL PRIMARY KEY,
    "ProductVersion" varchar(32) NOT NULL
);

-- Foreign keys are added after all tables to avoid circular dependency errors.
ALTER TABLE public."States" ADD CONSTRAINT "FK_States_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES public."Countries" ("Id") ON DELETE CASCADE;
ALTER TABLE public."Districts" ADD CONSTRAINT "FK_Districts_States_StateId" FOREIGN KEY ("StateId") REFERENCES public."States" ("Id") ON DELETE CASCADE;
ALTER TABLE public."Regions" ADD CONSTRAINT fk_regions_country FOREIGN KEY ("CountryId") REFERENCES public."Countries" ("Id");
ALTER TABLE public."Regions" ADD CONSTRAINT fk_regions_state FOREIGN KEY ("StateId") REFERENCES public."States" ("Id");
ALTER TABLE public."Regions" ADD CONSTRAINT fk_regions_district FOREIGN KEY ("DistrictId") REFERENCES public."Districts" ("Id");
ALTER TABLE public.application_menus ADD CONSTRAINT fk_menu_module FOREIGN KEY (module_id) REFERENCES public.application_modules (id);
ALTER TABLE public.application_menus ADD CONSTRAINT fk_parent_menu FOREIGN KEY (parent_menu_id) REFERENCES public.application_menus (id);
ALTER TABLE public.permissions ADD CONSTRAINT fk_permission_module FOREIGN KEY (module_id) REFERENCES public.application_modules (id);
ALTER TABLE public.user_roles ADD CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES public."Users" ("Id");
ALTER TABLE public.user_roles ADD CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES public.roles (id);
ALTER TABLE public.user_role_mappings ADD CONSTRAINT fk_user_role_mapping_user FOREIGN KEY (user_id) REFERENCES public."Users" ("Id");
ALTER TABLE public.user_role_mappings ADD CONSTRAINT fk_user_role_mapping_role FOREIGN KEY (role_id) REFERENCES public.roles (id);
ALTER TABLE public.role_permissions ADD CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES public.roles (id);
ALTER TABLE public.role_permissions ADD CONSTRAINT fk_role_permission_permission FOREIGN KEY (permission_id) REFERENCES public.permissions (id);
ALTER TABLE public.role_menu_access ADD CONSTRAINT fk_role_menu_role FOREIGN KEY (role_id) REFERENCES public.roles (id);
ALTER TABLE public.role_menu_access ADD CONSTRAINT fk_role_menu_menu FOREIGN KEY (menu_id) REFERENCES public.application_menus (id);
ALTER TABLE public.theatre_screens ADD CONSTRAINT fk_screen_location FOREIGN KEY (location_id) REFERENCES public."Locations" ("Id");
ALTER TABLE public.screens ADD CONSTRAINT fk_screen_venue FOREIGN KEY (venue_id) REFERENCES public.venues (id);
ALTER TABLE public.seats ADD CONSTRAINT fk_seat_screen FOREIGN KEY (screen_id) REFERENCES public.screens (id);
ALTER TABLE public.seats ADD CONSTRAINT fk_seat_category FOREIGN KEY (seat_category_id) REFERENCES public.seat_categories (id);
ALTER TABLE public.screen_seats ADD CONSTRAINT fk_screen_seat_screen FOREIGN KEY (screen_id) REFERENCES public.screens (id);
ALTER TABLE public.screen_seats ADD CONSTRAINT fk_screen_seat_schedule FOREIGN KEY ("ScheduleId") REFERENCES public."ShowSchedules" ("Id");
ALTER TABLE public."ShowSchedules" ADD CONSTRAINT "FK_ShowSchedules_LiveStreams_LiveStreamId" FOREIGN KEY ("LiveStreamId") REFERENCES public."LiveStreams" ("Id") ON DELETE RESTRICT;
ALTER TABLE public."ShowSchedules" ADD CONSTRAINT "FK_ShowSchedules_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES public."Locations" ("Id") ON DELETE CASCADE;
ALTER TABLE public."ShowSchedules" ADD CONSTRAINT "FK_ShowSchedules_Movies_MovieId" FOREIGN KEY ("MovieId") REFERENCES public."Movies" ("Id") ON DELETE RESTRICT;
ALTER TABLE public."ShowSchedules" ADD CONSTRAINT "FK_ShowSchedules_StandupShows_StandupShowId" FOREIGN KEY ("StandupShowId") REFERENCES public."StandupShows" ("Id") ON DELETE RESTRICT;
ALTER TABLE public."ShowSchedules" ADD CONSTRAINT fk_schedule_screen FOREIGN KEY (screen_id) REFERENCES public.screens (id);
ALTER TABLE public.show_seat_pricing ADD CONSTRAINT fk_pricing_schedule FOREIGN KEY (schedule_id) REFERENCES public."ShowSchedules" ("Id");
ALTER TABLE public.show_seat_pricing ADD CONSTRAINT fk_pricing_category FOREIGN KEY (seat_category_id) REFERENCES public.seat_categories (id);
ALTER TABLE public.bookings ADD CONSTRAINT fk_booking_user FOREIGN KEY (user_id) REFERENCES public."Users" ("Id");
ALTER TABLE public.bookings ADD CONSTRAINT fk_booking_schedule FOREIGN KEY (schedule_id) REFERENCES public."ShowSchedules" ("Id");
ALTER TABLE public.bookings ADD CONSTRAINT fk_booking_coupon FOREIGN KEY (coupon_id) REFERENCES public.coupons (id);
ALTER TABLE public.transactions ADD CONSTRAINT fk_transactions_user FOREIGN KEY (user_id) REFERENCES public."Users" ("Id");
ALTER TABLE public.transactions ADD CONSTRAINT fk_transactions_booking FOREIGN KEY (booking_id) REFERENCES public.bookings (id);
ALTER TABLE public.bookings ADD CONSTRAINT fk_booking_transaction FOREIGN KEY (transaction_id) REFERENCES public.transactions (id);
ALTER TABLE public.booking_drafts ADD CONSTRAINT fk_booking_draft_user FOREIGN KEY ("UserId") REFERENCES public."Users" ("Id");
ALTER TABLE public.booking_drafts ADD CONSTRAINT fk_booking_draft_schedule FOREIGN KEY ("ScheduleId") REFERENCES public."ShowSchedules" ("Id");
ALTER TABLE public."PaymentSessions" ADD CONSTRAINT fk_payment_session_booking FOREIGN KEY ("BookingId") REFERENCES public.bookings (id);
ALTER TABLE public.booking_transactions ADD CONSTRAINT fk_booking_transaction_booking FOREIGN KEY ("BookingId") REFERENCES public.bookings (id);
ALTER TABLE public.booking_items ADD CONSTRAINT fk_booking_item_booking FOREIGN KEY (booking_id) REFERENCES public.bookings (id) ON DELETE CASCADE;
ALTER TABLE public.booking_seats ADD CONSTRAINT fk_booking_seat_booking FOREIGN KEY (booking_id) REFERENCES public.bookings (id) ON DELETE CASCADE;
ALTER TABLE public.booking_seats ADD CONSTRAINT fk_booking_seat_item FOREIGN KEY (booking_item_id) REFERENCES public.booking_items (id);
ALTER TABLE public.booking_seats ADD CONSTRAINT fk_booking_seat_screen FOREIGN KEY (screen_seat_id) REFERENCES public.screen_seats (id);
ALTER TABLE public.tickets ADD CONSTRAINT fk_ticket_booking FOREIGN KEY (booking_id) REFERENCES public.bookings (id);
ALTER TABLE public.booked_seats ADD CONSTRAINT fk_booked_booking FOREIGN KEY (booking_id) REFERENCES public.bookings (id);
ALTER TABLE public.booked_seats ADD CONSTRAINT fk_booked_schedule FOREIGN KEY (schedule_id) REFERENCES public."ShowSchedules" ("Id");
ALTER TABLE public.booked_seats ADD CONSTRAINT fk_booked_seat FOREIGN KEY (seat_id) REFERENCES public.seats (id);
ALTER TABLE public.booked_seats ADD CONSTRAINT fk_booked_ticket FOREIGN KEY (ticket_id) REFERENCES public.tickets (id);
ALTER TABLE public.seat_locks ADD CONSTRAINT fk_seat_lock_user FOREIGN KEY (user_id) REFERENCES public."Users" ("Id");
ALTER TABLE public.seat_locks ADD CONSTRAINT fk_seat_lock_schedule FOREIGN KEY (schedule_id) REFERENCES public."ShowSchedules" ("Id");
ALTER TABLE public.seat_locks ADD CONSTRAINT fk_seat_lock_screen_seat FOREIGN KEY (screen_seat_id) REFERENCES public.screen_seats (id);
ALTER TABLE public.seat_locks ADD CONSTRAINT fk_seat_lock_booking FOREIGN KEY (booking_id) REFERENCES public.bookings (id);
ALTER TABLE public.booking_history ADD CONSTRAINT fk_booking_history_booking FOREIGN KEY (booking_id) REFERENCES public.bookings (id);
ALTER TABLE public.booking_status_history ADD CONSTRAINT fk_booking_status_booking FOREIGN KEY (booking_id) REFERENCES public.bookings (id);
ALTER TABLE public.coupon_usage ADD CONSTRAINT fk_coupon_usage_coupon FOREIGN KEY (coupon_id) REFERENCES public.coupons (id);
ALTER TABLE public.coupon_usage ADD CONSTRAINT fk_coupon_usage_booking FOREIGN KEY (booking_id) REFERENCES public.bookings (id);
ALTER TABLE public.coupon_usage ADD CONSTRAINT fk_coupon_usage_transaction FOREIGN KEY (transaction_id) REFERENCES public.transactions (id);
ALTER TABLE public.coupon_usage ADD CONSTRAINT fk_coupon_usage_user FOREIGN KEY (user_id) REFERENCES public."Users" ("Id");
ALTER TABLE public.coupon_audit_logs ADD CONSTRAINT fk_coupon_audit_coupon FOREIGN KEY (coupon_id) REFERENCES public.coupons (id);
ALTER TABLE public.refunds ADD CONSTRAINT fk_refund_booking FOREIGN KEY (booking_id) REFERENCES public.bookings (id);
ALTER TABLE public.refunds ADD CONSTRAINT fk_refund_transaction FOREIGN KEY (transaction_id) REFERENCES public.transactions (id);
ALTER TABLE public.refunds ADD CONSTRAINT fk_refund_user FOREIGN KEY (user_id) REFERENCES public."Users" ("Id");
ALTER TABLE public.refund_history ADD CONSTRAINT fk_refund_history_refund FOREIGN KEY (refund_id) REFERENCES public.refunds (id);
ALTER TABLE public.refund_action_logs ADD CONSTRAINT fk_refund_action_refund FOREIGN KEY (refund_id) REFERENCES public.refunds (id);
ALTER TABLE public.invoices ADD CONSTRAINT fk_invoice_booking FOREIGN KEY (booking_id) REFERENCES public.bookings (id);
ALTER TABLE public.invoices ADD CONSTRAINT fk_invoice_transaction FOREIGN KEY (transaction_id) REFERENCES public.transactions (id);
ALTER TABLE public.invoices ADD CONSTRAINT fk_invoice_user FOREIGN KEY (user_id) REFERENCES public."Users" ("Id");
ALTER TABLE public.invoice_items ADD CONSTRAINT fk_invoice_item_invoice FOREIGN KEY (invoice_id) REFERENCES public.invoices (id);
ALTER TABLE public.invoice_audit_logs ADD CONSTRAINT fk_invoice_audit_invoice FOREIGN KEY (invoice_id) REFERENCES public.invoices (id);
ALTER TABLE public.refund_invoices ADD CONSTRAINT fk_refund_invoice_refund FOREIGN KEY (refund_id) REFERENCES public.refunds (id);
ALTER TABLE public.refund_invoices ADD CONSTRAINT fk_refund_invoice_original FOREIGN KEY (original_invoice_id) REFERENCES public.invoices (id);
ALTER TABLE public.refund_invoices ADD CONSTRAINT fk_refund_invoice_new FOREIGN KEY (refund_invoice_id) REFERENCES public.invoices (id);
ALTER TABLE public.user_wallets ADD CONSTRAINT fk_wallet_user FOREIGN KEY (user_id) REFERENCES public."Users" ("Id");
ALTER TABLE public.wallet_transactions ADD CONSTRAINT fk_wallet_tx_wallet FOREIGN KEY (wallet_id) REFERENCES public.user_wallets (id);
ALTER TABLE public.wallet_transactions ADD CONSTRAINT fk_wallet_tx_user FOREIGN KEY (user_id) REFERENCES public."Users" ("Id");
ALTER TABLE public.wallet_transactions ADD CONSTRAINT fk_wallet_tx_booking FOREIGN KEY (booking_id) REFERENCES public.bookings (id);
ALTER TABLE public.wallet_transactions ADD CONSTRAINT fk_wallet_tx_transaction FOREIGN KEY (transaction_id) REFERENCES public.transactions (id);
ALTER TABLE public.wallet_transactions ADD CONSTRAINT fk_wallet_tx_refund FOREIGN KEY (refund_id) REFERENCES public.refunds (id);
ALTER TABLE public.loyalty_history ADD CONSTRAINT fk_loyalty_user FOREIGN KEY (user_id) REFERENCES public."Users" ("Id");
ALTER TABLE public.loyalty_history ADD CONSTRAINT fk_loyalty_booking FOREIGN KEY (booking_id) REFERENCES public.bookings (id);
ALTER TABLE public.loyalty_history ADD CONSTRAINT fk_loyalty_wallet_tx FOREIGN KEY (wallet_transaction_id) REFERENCES public.wallet_transactions (id);
ALTER TABLE public.user_notifications ADD CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES public."Users" ("Id");
ALTER TABLE public.user_notifications ADD CONSTRAINT fk_notification_template FOREIGN KEY (template_id) REFERENCES public.notification_templates (id);
ALTER TABLE public.notification_audit_logs ADD CONSTRAINT fk_notification_audit FOREIGN KEY (notification_id) REFERENCES public.user_notifications (id);
ALTER TABLE public.ticket_validation_logs ADD CONSTRAINT fk_validation_ticket FOREIGN KEY (ticket_id) REFERENCES public.tickets (id);
ALTER TABLE public.ticket_validation_logs ADD CONSTRAINT fk_validation_booking FOREIGN KEY (booking_id) REFERENCES public.bookings (id);
ALTER TABLE public.ticket_validation_logs ADD CONSTRAINT fk_validation_user FOREIGN KEY (user_id) REFERENCES public."Users" ("Id");
ALTER TABLE public.scanner_devices ADD CONSTRAINT fk_scanner_venue FOREIGN KEY (venue_id) REFERENCES public.venues (id);
ALTER TABLE public.scanner_devices ADD CONSTRAINT fk_scanner_screen FOREIGN KEY (screen_id) REFERENCES public.screens (id);

CREATE INDEX IF NOT EXISTS "IX_States_CountryId" ON public."States" ("CountryId");
CREATE INDEX IF NOT EXISTS "IX_Districts_StateId" ON public."Districts" ("StateId");
CREATE INDEX IF NOT EXISTS idx_application_menus_code ON public.application_menus (menu_code);
CREATE INDEX IF NOT EXISTS idx_application_menus_parent ON public.application_menus (parent_menu_id);
CREATE INDEX IF NOT EXISTS idx_permissions_code ON public.permissions (permission_code);
CREATE INDEX IF NOT EXISTS idx_user_roles_user ON public.user_roles (user_id);
CREATE INDEX IF NOT EXISTS idx_role_permissions_role ON public.role_permissions (role_id);
CREATE INDEX IF NOT EXISTS idx_role_menu_access_role ON public.role_menu_access (role_id);
CREATE INDEX IF NOT EXISTS idx_role_menu_access_menu ON public.role_menu_access (menu_id);
CREATE INDEX IF NOT EXISTS idx_show_schedule_screen ON public."ShowSchedules" (screen_id);
CREATE INDEX IF NOT EXISTS "IX_ShowSchedules_LiveStreamId" ON public."ShowSchedules" ("LiveStreamId");
CREATE INDEX IF NOT EXISTS "IX_ShowSchedules_LocationId" ON public."ShowSchedules" ("LocationId");
CREATE INDEX IF NOT EXISTS "IX_ShowSchedules_MovieId" ON public."ShowSchedules" ("MovieId");
CREATE INDEX IF NOT EXISTS "IX_ShowSchedules_StandupShowId" ON public."ShowSchedules" ("StandupShowId");
CREATE INDEX IF NOT EXISTS idx_bookings_user ON public.bookings (user_id);
CREATE INDEX IF NOT EXISTS idx_bookings_user_id ON public.bookings (user_id);
CREATE INDEX IF NOT EXISTS idx_bookings_schedule ON public.bookings (schedule_id);
CREATE INDEX IF NOT EXISTS idx_bookings_schedule_id ON public.bookings (schedule_id);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON public.bookings (booking_status);
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON public.transactions (user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_booking_id ON public.transactions (booking_id);
CREATE INDEX IF NOT EXISTS idx_transactions_transaction_ref ON public.transactions (transaction_ref);
CREATE INDEX IF NOT EXISTS idx_transactions_status ON public.transactions (status);
CREATE INDEX IF NOT EXISTS idx_transactions_created_at ON public.transactions (created_at);
CREATE INDEX IF NOT EXISTS idx_transactions_gateway_transaction_id ON public.transactions (gateway_transaction_id);
CREATE INDEX IF NOT EXISTS idx_booking_items_booking ON public.booking_items (booking_id);
CREATE INDEX IF NOT EXISTS idx_booking_seats_booking ON public.booking_seats (booking_id);
CREATE INDEX IF NOT EXISTS idx_screen_seats_schedule ON public.screen_seats ("ScheduleId");
CREATE UNIQUE INDEX IF NOT EXISTS uq_screen_seats_schedule_seat ON public.screen_seats ("ScheduleId", seat_row, seat_number);
CREATE INDEX IF NOT EXISTS idx_tickets_booking_id ON public.tickets (booking_id);
CREATE INDEX IF NOT EXISTS idx_ticket_qr_token ON public.tickets (qr_token);
CREATE INDEX IF NOT EXISTS idx_ticket_validation_status ON public.tickets (validation_status);
CREATE INDEX IF NOT EXISTS idx_booked_seats_booking ON public.booked_seats (booking_id);
CREATE INDEX IF NOT EXISTS idx_booked_seats_schedule ON public.booked_seats (schedule_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_booked_seat_schedule ON public.booked_seats (schedule_id, seat_id) WHERE booking_status IN ('BOOKED', 'LOCKED');
CREATE INDEX IF NOT EXISTS idx_seat_locks_schedule ON public.seat_locks (schedule_id);
CREATE INDEX IF NOT EXISTS idx_seat_locks_expiry ON public.seat_locks (expires_at, lock_status);
CREATE UNIQUE INDEX IF NOT EXISTS uq_active_seat_lock ON public.seat_locks (schedule_id, screen_seat_id) WHERE lock_status IN ('LOCKED', 'CONFIRMED');
CREATE INDEX IF NOT EXISTS idx_booking_history_booking_id ON public.booking_history (booking_id);
CREATE INDEX IF NOT EXISTS idx_booking_history_user_id ON public.booking_history (user_id);
CREATE INDEX IF NOT EXISTS idx_booking_history_action ON public.booking_history (action);
CREATE INDEX IF NOT EXISTS idx_booking_history_created_at ON public.booking_history (created_at);
CREATE INDEX IF NOT EXISTS idx_coupon_code ON public.coupons (coupon_code);
CREATE INDEX IF NOT EXISTS idx_coupon_status ON public.coupons (coupon_status);
CREATE INDEX IF NOT EXISTS idx_coupon_valid_to ON public.coupons (valid_to);
CREATE INDEX IF NOT EXISTS idx_coupon_usage_coupon ON public.coupon_usage (coupon_id);
CREATE INDEX IF NOT EXISTS idx_coupon_usage_user ON public.coupon_usage (user_id);
CREATE INDEX IF NOT EXISTS idx_refunds_booking_id ON public.refunds (booking_id);
CREATE INDEX IF NOT EXISTS idx_refunds_transaction_id ON public.refunds (transaction_id);
CREATE INDEX IF NOT EXISTS idx_refunds_user_id ON public.refunds (user_id);
CREATE INDEX IF NOT EXISTS idx_refunds_status ON public.refunds (refund_status);
CREATE INDEX IF NOT EXISTS idx_refunds_created_at ON public.refunds (created_at);
CREATE INDEX IF NOT EXISTS idx_invoice_booking ON public.invoices (booking_id);
CREATE INDEX IF NOT EXISTS idx_invoice_transaction ON public.invoices (transaction_id);
CREATE INDEX IF NOT EXISTS idx_invoice_user ON public.invoices (user_id);
CREATE INDEX IF NOT EXISTS idx_invoice_number ON public.invoices (invoice_number);
CREATE INDEX IF NOT EXISTS idx_invoice_date ON public.invoices (invoice_date);
CREATE INDEX IF NOT EXISTS idx_wallet_user ON public.user_wallets (user_id);
CREATE INDEX IF NOT EXISTS idx_wallet_tx_wallet ON public.wallet_transactions (wallet_id);
CREATE INDEX IF NOT EXISTS idx_wallet_tx_user ON public.wallet_transactions (user_id);
CREATE INDEX IF NOT EXISTS idx_wallet_tx_booking ON public.wallet_transactions (booking_id);
CREATE INDEX IF NOT EXISTS idx_wallet_tx_created ON public.wallet_transactions (created_at);
CREATE INDEX IF NOT EXISTS idx_notification_user ON public.user_notifications (user_id);
CREATE INDEX IF NOT EXISTS idx_notification_type ON public.user_notifications (notification_type);
CREATE INDEX IF NOT EXISTS idx_notification_status ON public.user_notifications (status);
CREATE INDEX IF NOT EXISTS idx_notification_created_at ON public.user_notifications (created_at);
CREATE INDEX IF NOT EXISTS idx_otp_recipient ON public.otp_management (recipient);
CREATE INDEX IF NOT EXISTS idx_otp_status ON public.otp_management (status);
CREATE INDEX IF NOT EXISTS idx_validation_ticket ON public.ticket_validation_logs (ticket_id);
CREATE INDEX IF NOT EXISTS idx_validation_booking ON public.ticket_validation_logs (booking_id);
CREATE INDEX IF NOT EXISTS idx_validation_scanned_at ON public.ticket_validation_logs (scanned_at);
CREATE INDEX IF NOT EXISTS idx_access_logs_user ON public.access_audit_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_frontend_version_version ON public.frontend_version_control (version);
CREATE INDEX IF NOT EXISTS idx_frontend_version_environment ON public.frontend_version_control (environment);
CREATE INDEX IF NOT EXISTS idx_frontend_version_status ON public.frontend_version_control (deployment_status);
CREATE INDEX IF NOT EXISTS idx_frontend_version_deployed_at ON public.frontend_version_control (deployed_at);

CREATE OR REPLACE TRIGGER trg_assign_default_role
AFTER INSERT ON public."Users"
FOR EACH ROW EXECUTE FUNCTION public.fn_assign_default_role();

CREATE OR REPLACE TRIGGER trg_bookings_updated_at
BEFORE UPDATE ON public.bookings
FOR EACH ROW EXECUTE FUNCTION public.fn_update_updated_at();

CREATE OR REPLACE TRIGGER trg_set_booking_reference
BEFORE INSERT ON public.bookings
FOR EACH ROW EXECUTE FUNCTION public.fn_set_booking_reference();

CREATE OR REPLACE TRIGGER trg_track_booking_status
AFTER UPDATE ON public.bookings
FOR EACH ROW EXECUTE FUNCTION public.fn_track_booking_status();

CREATE OR REPLACE TRIGGER trg_transactions_updated_at
BEFORE UPDATE ON public.transactions
FOR EACH ROW EXECUTE FUNCTION public.fn_update_updated_at();

CREATE OR REPLACE TRIGGER trg_tickets_updated_at
BEFORE UPDATE ON public.tickets
FOR EACH ROW EXECUTE FUNCTION public.fn_update_updated_at();

CREATE OR REPLACE TRIGGER trg_refunds_updated_at
BEFORE UPDATE ON public.refunds
FOR EACH ROW EXECUTE FUNCTION public.fn_update_updated_at();

CREATE OR REPLACE TRIGGER trg_refund_audit
AFTER UPDATE ON public.refunds
FOR EACH ROW
WHEN (OLD.refund_status IS DISTINCT FROM NEW.refund_status)
EXECUTE FUNCTION public.fn_refund_audit();

CREATE OR REPLACE TRIGGER trg_invoices_updated_at
BEFORE UPDATE ON public.invoices
FOR EACH ROW EXECUTE FUNCTION public.fn_update_updated_at();

CREATE OR REPLACE TRIGGER trg_notification_template_updated_at
BEFORE UPDATE ON public.notification_templates
FOR EACH ROW EXECUTE FUNCTION public.fn_update_updated_at();

CREATE OR REPLACE TRIGGER trg_notification_updated_at
BEFORE UPDATE ON public.user_notifications
FOR EACH ROW EXECUTE FUNCTION public.fn_update_updated_at();

CREATE OR REPLACE TRIGGER trg_wallet_balance_update
AFTER INSERT ON public.wallet_transactions
FOR EACH ROW EXECUTE FUNCTION public.fn_wallet_balance_update();

INSERT INTO public.roles (role_code, role_name, role_description, is_system_role)
VALUES
    ('ADMIN', 'Administrator', 'Full administrative access', true),
    ('USER', 'User', 'Default customer role', true)
ON CONFLICT (role_code) DO UPDATE
SET role_name = EXCLUDED.role_name,
    role_description = EXCLUDED.role_description,
    is_system_role = EXCLUDED.is_system_role;

INSERT INTO public.seat_categories (category_name, category_code, price_multiplier, color_code)
VALUES
    ('Regular', 'REGULAR', 1.00, '#64748b'),
    ('Premium', 'PREMIUM', 1.50, '#2563eb'),
    ('VIP', 'VIP', 2.00, '#c026d3')
ON CONFLICT (category_code) DO NOTHING;

INSERT INTO public.loyalty_config (config_name, points_per_amount, minimum_redeem_points, point_value, max_redeem_percentage, is_active)
VALUES ('DEFAULT', 1.00, 100, 1.00, 20.00, true)
ON CONFLICT DO NOTHING;

DROP VIEW IF EXISTS public.vw_wallet_summary;
DROP VIEW IF EXISTS public.vw_user_application_menus;
DROP VIEW IF EXISTS public.vw_user_access_matrix;
DROP VIEW IF EXISTS public.vw_ticket_validation_summary;
DROP VIEW IF EXISTS public.vw_refund_summary;
DROP VIEW IF EXISTS public.vw_notification_center;
DROP VIEW IF EXISTS public.vw_invoice_summary;
DROP VIEW IF EXISTS public.vw_enterprise_activity_logs;
DROP VIEW IF EXISTS public.vw_coupon_analytics;
DROP VIEW IF EXISTS public.vw_home_show_listing;
DROP VIEW IF EXISTS public.vw_booking_transaction_summary;
DROP VIEW IF EXISTS public.vw_booking_complete_details;
DROP VIEW IF EXISTS public.vw_admin_user_management;
DROP VIEW IF EXISTS public.vw_admin_transaction_complete;

CREATE OR REPLACE VIEW public.vw_admin_transaction_complete AS
SELECT
    t.id AS transaction_id,
    COALESCE(t.transaction_ref, '') AS transaction_ref,
    COALESCE(t.transaction_type, '') AS transaction_type,
    COALESCE(t.payment_method, '') AS payment_method,
    COALESCE(t.gateway_name, '') AS gateway_name,
    COALESCE(t.amount, 0) AS amount,
    COALESCE(t.currency, 'INR') AS currency,
    COALESCE(t.status, '') AS transaction_status,
    COALESCE(u."Name", '') AS user_name,
    COALESCE(u."Email", '') AS user_email,
    COALESCE(b.booking_ref, '') AS booking_ref,
    COALESCE(b.booking_status, '') AS booking_status,
    COALESCE(b.total_amount, 0) AS total_amount,
    COALESCE(b.discount_amount, 0) AS discount_amount,
    COALESCE(b.tax_amount, 0) AS tax_amount,
    COALESCE(b.payable_amount, 0) AS payable_amount,
    COALESCE(c.coupon_code, '') AS coupon_code,
    COALESCE(sch."Type", '') AS show_type,
    COALESCE(m."Title", ssu."Title", ls."Title", '') AS show_title,
    COALESCE(loc."Country", '') AS country,
    COALESCE(loc."State", '') AS state,
    COALESCE(loc."Area", '') AS area,
    COALESCE(r.refund_status, '') AS refund_status,
    r.refund_amount,
    t.created_at
FROM public.transactions t
LEFT JOIN public.bookings b ON t.booking_id = b.id OR b.transaction_id = t.id
LEFT JOIN public."Users" u ON COALESCE(b.user_id, t.user_id) = u."Id"
LEFT JOIN public."ShowSchedules" sch ON b.schedule_id = sch."Id"
LEFT JOIN public."Movies" m ON sch."MovieId" = m."Id"
LEFT JOIN public."StandupShows" ssu ON sch."StandupShowId" = ssu."Id"
LEFT JOIN public."LiveStreams" ls ON sch."LiveStreamId" = ls."Id"
LEFT JOIN public."Locations" loc ON sch."LocationId" = loc."Id"
LEFT JOIN public.refunds r ON t.id = r.transaction_id
LEFT JOIN public.coupons c ON b.coupon_id = c.id;

CREATE OR REPLACE VIEW public.vw_admin_user_management AS
SELECT
    u."Id" AS user_id,
    u."Name" AS user_name,
    u."Email" AS user_email,
    u."Mobile" AS user_mobile,
    u.is_active,
    u.is_deleted,
    u."CreatedAt" AS created_at,
    count(b.id) AS total_bookings,
    COALESCE(sum(b.payable_amount), 0) AS total_spent
FROM public."Users" u
LEFT JOIN public.bookings b ON u."Id" = b.user_id
GROUP BY u."Id";

CREATE OR REPLACE VIEW public.vw_booking_complete_details AS
SELECT
    b.id AS booking_id,
    b.booking_ref,
    u."Id" AS user_id,
    u."Name" AS user_name,
    u."Email" AS user_email,
    ss."Type" AS show_type,
    COALESCE(m."Title", st."Title", ls."Title") AS show_title,
    COALESCE(l."Area", 'N/A') AS location_name,
    ss."StartTime" AS start_time,
    COALESCE(seat_list.seat_numbers, 'N/A') AS seat_numbers,
    COALESCE(b.booking_status, 'PENDING') AS booking_status,
    COALESCE(b.payment_status, 'PENDING') AS payment_status,
    b.total_tickets,
    b.total_amount,
    b.tax_amount,
    b.discount_amount,
    b.payable_amount,
    COALESCE(tx.transaction_ref::text, bt."TransactionRef"::text, 'N/A') AS transaction_ref,
    COALESCE(tx.payment_method::text, bt."PaymentMethod"::text, 'N/A') AS payment_method,
    COALESCE(tx.gateway_name::text, CASE WHEN bt."Id" IS NOT NULL THEN 'DUMMY_GATEWAY' END, 'N/A') AS gateway_name,
    COALESCE(tx.status::text, bt."PaymentStatus"::text, 'PENDING') AS transaction_status,
    b.booked_at,
    b.confirmed_at,
    b.cancelled_at,
    b.created_at,
    CASE WHEN b.booking_status = 'FAILED' THEN 1 ELSE 0 END AS is_error
FROM public.bookings b
JOIN public."Users" u ON b.user_id = u."Id"
JOIN public."ShowSchedules" ss ON b.schedule_id = ss."Id"
LEFT JOIN public."Movies" m ON ss."MovieId" = m."Id"
LEFT JOIN public."StandupShows" st ON ss."StandupShowId" = st."Id"
LEFT JOIN public."LiveStreams" ls ON ss."LiveStreamId" = ls."Id"
LEFT JOIN public."Locations" l ON ss."LocationId" = l."Id"
LEFT JOIN LATERAL (
    SELECT string_agg(tk.seat_number, ', ' ORDER BY tk.seat_number) AS seat_numbers
    FROM public.tickets tk
    WHERE tk.booking_id = b.id
) seat_list ON true
LEFT JOIN LATERAL (
    SELECT t.*
    FROM public.transactions t
    WHERE t.id = b.transaction_id OR t.booking_id = b.id
    ORDER BY
        CASE WHEN t.id = b.transaction_id THEN 0 ELSE 1 END,
        t.completed_at DESC NULLS LAST,
        t.created_at DESC NULLS LAST
    LIMIT 1
) tx ON true
LEFT JOIN LATERAL (
    SELECT bt_inner.*
    FROM public.booking_transactions bt_inner
    WHERE bt_inner."BookingId" = b.id
    ORDER BY bt_inner."PaidAt" DESC NULLS LAST, bt_inner."CreatedAt" DESC NULLS LAST
    LIMIT 1
) bt ON true;

CREATE OR REPLACE VIEW public.vw_booking_transaction_summary AS
SELECT
    b.id AS booking_id,
    COALESCE(b.booking_ref, '') AS booking_ref,
    u."Id" AS user_id,
    COALESCE(u."Name", '') AS user_name,
    COALESCE(u."Email", '') AS user_email,
    COALESCE(s."Type", '') AS show_type,
    COALESCE(m."Title", ss."Title", ls."Title", '') AS show_title,
    COALESCE(b.booking_status, '') AS booking_status,
    COALESCE(tx.id, bt."Id") AS transaction_id,
    COALESCE(tx.transaction_ref::text, bt."TransactionRef"::text, '') AS transaction_ref,
    COALESCE(tx.payment_method::text, bt."PaymentMethod"::text, '') AS payment_method,
    COALESCE(tx.amount, bt."Amount", 0) AS transaction_amount,
    COALESCE(tx.currency, 'INR') AS currency,
    COALESCE(tx.status::text, bt."PaymentStatus"::text, '') AS transaction_status,
    COALESCE(tx.gateway_name::text, CASE WHEN bt."Id" IS NOT NULL THEN 'DUMMY_GATEWAY' END, '') AS gateway_name,
    COALESCE(tx.failure_reason, '') AS failure_reason,
    CASE WHEN lower(COALESCE(tx.status::text, bt."PaymentStatus"::text, '')) = 'failed' THEN 1 ELSE 0 END AS is_payment_error,
    COALESCE(b.total_amount, 0) AS total_amount,
    b.created_at AS booking_created_at,
    COALESCE(tx.completed_at, bt."PaidAt"::timestamp without time zone) AS completed_at
FROM public.bookings b
LEFT JOIN LATERAL (
    SELECT t.*
    FROM public.transactions t
    WHERE t.id = b.transaction_id OR t.booking_id = b.id
    ORDER BY
        CASE WHEN t.id = b.transaction_id THEN 0 ELSE 1 END,
        t.completed_at DESC NULLS LAST,
        t.created_at DESC NULLS LAST
    LIMIT 1
) tx ON true
LEFT JOIN LATERAL (
    SELECT bt_inner.*
    FROM public.booking_transactions bt_inner
    WHERE bt_inner."BookingId" = b.id
    ORDER BY bt_inner."PaidAt" DESC NULLS LAST, bt_inner."CreatedAt" DESC NULLS LAST
    LIMIT 1
) bt ON true
LEFT JOIN public."Users" u ON b.user_id = u."Id"
LEFT JOIN public."ShowSchedules" s ON b.schedule_id = s."Id"
LEFT JOIN public."Movies" m ON s."MovieId" = m."Id"
LEFT JOIN public."StandupShows" ss ON s."StandupShowId" = ss."Id"
LEFT JOIN public."LiveStreams" ls ON s."LiveStreamId" = ls."Id";

CREATE OR REPLACE VIEW public.vw_coupon_analytics AS
SELECT
    c.id AS coupon_id,
    c.coupon_code,
    c.coupon_name,
    c.discount_type,
    c.discount_value,
    c.minimum_booking_amount,
    c.maximum_discount_amount,
    c.usage_limit,
    c.used_count,
    c.valid_from,
    c.valid_to,
    c.coupon_status,
    count(cu.id) AS total_usages,
    COALESCE(sum(cu.discount_amount), 0) AS total_discount_given,
    COALESCE(sum(cu.final_amount), 0) AS total_revenue_generated,
    CASE WHEN c.valid_to < CURRENT_TIMESTAMP THEN 'EXPIRED' ELSE c.coupon_status END AS computed_status
FROM public.coupons c
LEFT JOIN public.coupon_usage cu ON c.id = cu.coupon_id
GROUP BY c.id;

CREATE OR REPLACE VIEW public.vw_home_show_listing AS
SELECT
    s."Id" AS schedule_id,
    CASE
        WHEN s."MovieId" IS NOT NULL THEN 'Movie'
        WHEN s."StandupShowId" IS NOT NULL THEN 'Standup'
        WHEN s."LiveStreamId" IS NOT NULL THEN 'Live'
        ELSE COALESCE(NULLIF(s."Type", ''), 'Movie')
    END AS show_type,
    COALESCE(s."MovieId", s."StandupShowId", s."LiveStreamId", 0) AS show_id,
    COALESCE(m."Title", st."Title", ls."Title", 'Untitled Show') AS title,
    CASE
        WHEN m."Id" IS NOT NULL THEN concat_ws(' | ', NULLIF(m."Director", ''), NULLIF(m."Producer", ''), NULLIF(m."Cast", ''))
        WHEN st."Id" IS NOT NULL THEN 'Comedian: ' || st."Comedian"
        WHEN ls."Id" IS NOT NULL THEN 'Host: ' || ls."Host"
        ELSE ''
    END AS "Description",
    ''::text AS "PosterUrl",
    s."StartTime" AS start_time,
    s."EndTime" AS end_time,
    COALESCE(l."Area", '') AS location,
    COALESCE(l."State", '') AS state,
    COALESCE(l."Country", '') AS country
FROM public."ShowSchedules" s
LEFT JOIN public."Movies" m ON s."MovieId" = m."Id"
LEFT JOIN public."StandupShows" st ON s."StandupShowId" = st."Id"
LEFT JOIN public."LiveStreams" ls ON s."LiveStreamId" = ls."Id"
LEFT JOIN public."Locations" l ON s."LocationId" = l."Id";

CREATE OR REPLACE VIEW public.vw_enterprise_activity_logs AS
SELECT u."Id"::bigint AS entity_id, 'USER'::text AS module, 'USER_REGISTERED'::varchar AS action,
       u."Name" AS user_name, u."Email" AS user_email, NULL::text AS reference_no,
       'SUCCESS'::varchar AS status, 'New user account created'::text AS description,
       NULL::text AS error_message, u."CreatedAt"::timestamp without time zone AS activity_time
FROM public."Users" u
UNION ALL
SELECT t.id, 'TRANSACTION', t.status, u."Name", u."Email", t.transaction_ref, t.status,
       COALESCE(t.description, 'Transaction processed'), t.failure_reason, COALESCE(t.completed_at, t.created_at)
FROM public.transactions t
LEFT JOIN public."Users" u ON u."Id" = t.user_id
UNION ALL
SELECT b.id, 'BOOKING', b.booking_status, u."Name", u."Email", b.booking_ref, b.booking_status,
       'Ticket booking activity', NULL::text, b.created_at
FROM public.bookings b
LEFT JOIN public."Users" u ON u."Id" = b.user_id
UNION ALL
SELECT al.id::bigint, 'SYSTEM', al.action::varchar, u."Name", u."Email", NULL::text, al.status::varchar,
       al.description, al.error_message, al.created_at
FROM public.activity_logs al
LEFT JOIN public."Users" u ON u."Id" = al.user_id;

CREATE OR REPLACE VIEW public.vw_invoice_summary AS
SELECT
    i.id AS invoice_id,
    i.invoice_number,
    i.invoice_type,
    i.invoice_status,
    i.invoice_date,
    b.booking_ref,
    t.transaction_ref,
    u."Name" AS customer_name,
    u."Email" AS customer_email,
    i.subtotal_amount,
    i.cgst_amount,
    i.sgst_amount,
    i.igst_amount,
    i.discount_amount,
    i.total_amount,
    i.currency,
    i.gstin,
    i.invoice_pdf_url,
    CASE WHEN i.invoice_status = 'FAILED' THEN 1 ELSE 0 END AS is_invoice_error
FROM public.invoices i
JOIN public.bookings b ON i.booking_id = b.id
LEFT JOIN public.transactions t ON i.transaction_id = t.id
JOIN public."Users" u ON i.user_id = u."Id";

CREATE OR REPLACE VIEW public.vw_notification_center AS
SELECT
    un.id AS notification_id,
    u."Name" AS user_name,
    u."Email" AS user_email,
    nt.template_code,
    nt.template_name,
    un.notification_type,
    un.title,
    un.message,
    un.status,
    un.priority,
    un.sent_at,
    un.delivered_at,
    un.read_at,
    un.retry_count,
    un.failure_reason,
    un.created_at,
    CASE WHEN un.status = 'FAILED' THEN 1 ELSE 0 END AS is_error
FROM public.user_notifications un
JOIN public."Users" u ON un.user_id = u."Id"
LEFT JOIN public.notification_templates nt ON un.template_id = nt.id;

CREATE OR REPLACE VIEW public.vw_refund_summary AS
SELECT
    r.id AS refund_id,
    r.refund_ref,
    b.booking_ref,
    t.transaction_ref,
    u."Id" AS user_id,
    u."Name" AS user_name,
    u."Email" AS user_email,
    r.refund_amount,
    r.refund_reason,
    r.refund_status,
    r.refund_method,
    r.workflow_action,
    r.approved_by,
    r.approved_at,
    r.rejected_by,
    r.rejected_at,
    r.retried_by,
    r.retried_at,
    r.gateway_refund_id,
    r.failure_reason,
    r.requested_at,
    r.processed_at,
    r.created_at,
    r.updated_at,
    r.admin_notes,
    CASE WHEN r.refund_status = 'SUCCESS' THEN 0 ELSE 1 END AS is_refund_error
FROM public.refunds r
JOIN public.bookings b ON r.booking_id = b.id
JOIN public.transactions t ON r.transaction_id = t.id
JOIN public."Users" u ON r.user_id = u."Id";

CREATE OR REPLACE VIEW public.vw_ticket_validation_summary AS
SELECT
    tvl.id AS validation_log_id,
    t.id AS ticket_id,
    t.ticket_number,
    b.booking_ref,
    u."Name" AS user_name,
    u."Email" AS user_email,
    tvl.validation_status,
    tvl.validation_result,
    tvl.gate_name,
    tvl.device_id,
    tvl.scanner_user,
    tvl.scanned_at,
    t.validation_count,
    t.last_scanned_at,
    CASE WHEN tvl.validation_result = 'SUCCESS' THEN 0 ELSE 1 END AS is_security_issue
FROM public.ticket_validation_logs tvl
JOIN public.tickets t ON tvl.ticket_id = t.id
JOIN public.bookings b ON tvl.booking_id = b.id
LEFT JOIN public."Users" u ON tvl.user_id = u."Id";

CREATE OR REPLACE VIEW public.vw_user_access_matrix AS
SELECT
    u."Id" AS user_id,
    u."Name" AS user_name,
    u."Email" AS user_email,
    r.role_code,
    r.role_name,
    am.module_code,
    am.module_name,
    p.permission_code,
    p.permission_name,
    p.action_type,
    ur.assigned_at,
    ur.is_active
FROM public."Users" u
JOIN public.user_roles ur ON u."Id" = ur.user_id
JOIN public.roles r ON ur.role_id = r.id
JOIN public.role_permissions rp ON r.id = rp.role_id
JOIN public.permissions p ON rp.permission_id = p.id
JOIN public.application_modules am ON p.module_id = am.id;

CREATE OR REPLACE VIEW public.vw_user_application_menus AS
SELECT
    u."Id" AS user_id,
    u."Name" AS user_name,
    r.role_code,
    m.id AS menu_id,
    m.menu_code,
    m.menu_name,
    m.parent_menu_id,
    parent_menu.menu_name AS parent_menu_name,
    m.route_path,
    m.icon_name,
    m.menu_level,
    m.display_order,
    rma.can_view,
    rma.can_create,
    rma.can_update,
    rma.can_delete
FROM public."Users" u
JOIN public.user_roles ur ON u."Id" = ur.user_id
JOIN public.roles r ON ur.role_id = r.id
JOIN public.role_menu_access rma ON r.id = rma.role_id
JOIN public.application_menus m ON rma.menu_id = m.id
LEFT JOIN public.application_menus parent_menu ON m.parent_menu_id = parent_menu.id
WHERE ur.is_active = true
  AND m.is_active = true
  AND rma.can_view = true;

CREATE OR REPLACE VIEW public.vw_wallet_summary AS
SELECT
    uw.id AS wallet_id,
    u."Id" AS user_id,
    u."Name" AS user_name,
    u."Email" AS user_email,
    uw.wallet_balance,
    uw.blocked_balance,
    uw.loyalty_points,
    uw.wallet_status,
    uw.last_transaction_at,
    count(wt.id) AS total_wallet_transactions,
    COALESCE(sum(CASE WHEN wt.entry_type = 'CREDIT' THEN wt.amount ELSE 0 END), 0) AS total_credits,
    COALESCE(sum(CASE WHEN wt.entry_type = 'DEBIT' THEN wt.amount ELSE 0 END), 0) AS total_debits
FROM public.user_wallets uw
JOIN public."Users" u ON uw.user_id = u."Id"
LEFT JOIN public.wallet_transactions wt ON uw.id = wt.wallet_id
GROUP BY uw.id, u."Id";

ALTER TABLE public.vw_admin_transaction_complete OWNER TO postgres;
ALTER TABLE public.vw_admin_user_management OWNER TO postgres;
ALTER TABLE public.vw_booking_complete_details OWNER TO postgres;
ALTER TABLE public.vw_booking_transaction_summary OWNER TO postgres;
ALTER TABLE public.vw_coupon_analytics OWNER TO postgres;
ALTER TABLE public.vw_home_show_listing OWNER TO postgres;
ALTER TABLE public.vw_enterprise_activity_logs OWNER TO postgres;
ALTER TABLE public.vw_invoice_summary OWNER TO postgres;
ALTER TABLE public.vw_notification_center OWNER TO postgres;
ALTER TABLE public.vw_refund_summary OWNER TO postgres;
ALTER TABLE public.vw_ticket_validation_summary OWNER TO postgres;
ALTER TABLE public.vw_user_access_matrix OWNER TO postgres;
ALTER TABLE public.vw_user_application_menus OWNER TO postgres;
ALTER TABLE public.vw_wallet_summary OWNER TO postgres;

COMMIT;
